### ISSUE TITLE
change button " جاهز للتحدي " 

### ISSUE THREAD

**Issue by TikoKershless** [heshamMassoud/Kershless-website#45]
Change the button size and color to light blue and same rounded edge rectangle as the above rectangles

**Comment by heshamMassoud** [comment]
@TikoKershless 

This is a duplicate issue: https://github.com/heshamMassoud/Kershless/issues/19
What do you mean change button size? to what exactly?
Light Blue? What is the Hex code exactly?

Also, please check your open issues or open issues in general, before creating new ones, rather than creating duplicated issues, because we will use the issues as a status review in the meetings. :wink:
